// Generated by gencpp from file path_planning_vrep_simulation/Path.msg
// DO NOT EDIT!


#ifndef PATH_PLANNING_VREP_SIMULATION_MESSAGE_PATH_H
#define PATH_PLANNING_VREP_SIMULATION_MESSAGE_PATH_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <path_planning_vrep_simulation/Point2d.h>

namespace path_planning_vrep_simulation
{
template <class ContainerAllocator>
struct Path_
{
  typedef Path_<ContainerAllocator> Type;

  Path_()
    : platform_id(0)
    , path_points()  {
    }
  Path_(const ContainerAllocator& _alloc)
    : platform_id(0)
    , path_points(_alloc)  {
  (void)_alloc;
    }



   typedef int32_t _platform_id_type;
  _platform_id_type platform_id;

   typedef std::vector< ::path_planning_vrep_simulation::Point2d_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::path_planning_vrep_simulation::Point2d_<ContainerAllocator> >::other >  _path_points_type;
  _path_points_type path_points;





  typedef boost::shared_ptr< ::path_planning_vrep_simulation::Path_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::path_planning_vrep_simulation::Path_<ContainerAllocator> const> ConstPtr;

}; // struct Path_

typedef ::path_planning_vrep_simulation::Path_<std::allocator<void> > Path;

typedef boost::shared_ptr< ::path_planning_vrep_simulation::Path > PathPtr;
typedef boost::shared_ptr< ::path_planning_vrep_simulation::Path const> PathConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::path_planning_vrep_simulation::Path_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::path_planning_vrep_simulation::Path_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace path_planning_vrep_simulation

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'path_planning_vrep_simulation': ['/home/konst/path_planning_algorithm_vrep_test/src/path_planning_vrep_simulation-master/msg'], 'std_msgs': ['/opt/ros/melodic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::path_planning_vrep_simulation::Path_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::path_planning_vrep_simulation::Path_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::path_planning_vrep_simulation::Path_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::path_planning_vrep_simulation::Path_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::path_planning_vrep_simulation::Path_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::path_planning_vrep_simulation::Path_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::path_planning_vrep_simulation::Path_<ContainerAllocator> >
{
  static const char* value()
  {
    return "6585a46cc084ae3da85218f36f44c7f9";
  }

  static const char* value(const ::path_planning_vrep_simulation::Path_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x6585a46cc084ae3dULL;
  static const uint64_t static_value2 = 0xa85218f36f44c7f9ULL;
};

template<class ContainerAllocator>
struct DataType< ::path_planning_vrep_simulation::Path_<ContainerAllocator> >
{
  static const char* value()
  {
    return "path_planning_vrep_simulation/Path";
  }

  static const char* value(const ::path_planning_vrep_simulation::Path_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::path_planning_vrep_simulation::Path_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32     platform_id\n"
"Point2d[] path_points\n"
"\n"
"================================================================================\n"
"MSG: path_planning_vrep_simulation/Point2d\n"
"float32 x\n"
"float32 y\n"
;
  }

  static const char* value(const ::path_planning_vrep_simulation::Path_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::path_planning_vrep_simulation::Path_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.platform_id);
      stream.next(m.path_points);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Path_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::path_planning_vrep_simulation::Path_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::path_planning_vrep_simulation::Path_<ContainerAllocator>& v)
  {
    s << indent << "platform_id: ";
    Printer<int32_t>::stream(s, indent + "  ", v.platform_id);
    s << indent << "path_points[]" << std::endl;
    for (size_t i = 0; i < v.path_points.size(); ++i)
    {
      s << indent << "  path_points[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::path_planning_vrep_simulation::Point2d_<ContainerAllocator> >::stream(s, indent + "    ", v.path_points[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // PATH_PLANNING_VREP_SIMULATION_MESSAGE_PATH_H
