// Generated by gencpp from file path_planning_vrep_simulation/Step.msg
// DO NOT EDIT!


#ifndef PATH_PLANNING_VREP_SIMULATION_MESSAGE_STEP_H
#define PATH_PLANNING_VREP_SIMULATION_MESSAGE_STEP_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <path_planning_vrep_simulation/Point2d.h>
#include <path_planning_vrep_simulation/Point2d.h>

namespace path_planning_vrep_simulation
{
template <class ContainerAllocator>
struct Step_
{
  typedef Step_<ContainerAllocator> Type;

  Step_()
    : number(0)
    , start()
    , finish()
    , duration(0.0)  {
    }
  Step_(const ContainerAllocator& _alloc)
    : number(0)
    , start(_alloc)
    , finish(_alloc)
    , duration(0.0)  {
  (void)_alloc;
    }



   typedef int32_t _number_type;
  _number_type number;

   typedef  ::path_planning_vrep_simulation::Point2d_<ContainerAllocator>  _start_type;
  _start_type start;

   typedef  ::path_planning_vrep_simulation::Point2d_<ContainerAllocator>  _finish_type;
  _finish_type finish;

   typedef float _duration_type;
  _duration_type duration;





  typedef boost::shared_ptr< ::path_planning_vrep_simulation::Step_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::path_planning_vrep_simulation::Step_<ContainerAllocator> const> ConstPtr;

}; // struct Step_

typedef ::path_planning_vrep_simulation::Step_<std::allocator<void> > Step;

typedef boost::shared_ptr< ::path_planning_vrep_simulation::Step > StepPtr;
typedef boost::shared_ptr< ::path_planning_vrep_simulation::Step const> StepConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::path_planning_vrep_simulation::Step_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::path_planning_vrep_simulation::Step_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace path_planning_vrep_simulation

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'path_planning_vrep_simulation': ['/home/konst/path_planning_vrep_simulation/src/path_planning_vrep_simulation-master/msg'], 'std_msgs': ['/opt/ros/melodic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::path_planning_vrep_simulation::Step_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::path_planning_vrep_simulation::Step_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::path_planning_vrep_simulation::Step_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::path_planning_vrep_simulation::Step_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::path_planning_vrep_simulation::Step_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::path_planning_vrep_simulation::Step_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::path_planning_vrep_simulation::Step_<ContainerAllocator> >
{
  static const char* value()
  {
    return "e1ec2cd1e2aeecbfde1f919967aaf705";
  }

  static const char* value(const ::path_planning_vrep_simulation::Step_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xe1ec2cd1e2aeecbfULL;
  static const uint64_t static_value2 = 0xde1f919967aaf705ULL;
};

template<class ContainerAllocator>
struct DataType< ::path_planning_vrep_simulation::Step_<ContainerAllocator> >
{
  static const char* value()
  {
    return "path_planning_vrep_simulation/Step";
  }

  static const char* value(const ::path_planning_vrep_simulation::Step_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::path_planning_vrep_simulation::Step_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32   number\n\
Point2d start\n\
Point2d finish\n\
float32 duration\n\
================================================================================\n\
MSG: path_planning_vrep_simulation/Point2d\n\
float32 x\n\
float32 y\n\
";
  }

  static const char* value(const ::path_planning_vrep_simulation::Step_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::path_planning_vrep_simulation::Step_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.number);
      stream.next(m.start);
      stream.next(m.finish);
      stream.next(m.duration);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Step_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::path_planning_vrep_simulation::Step_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::path_planning_vrep_simulation::Step_<ContainerAllocator>& v)
  {
    s << indent << "number: ";
    Printer<int32_t>::stream(s, indent + "  ", v.number);
    s << indent << "start: ";
    s << std::endl;
    Printer< ::path_planning_vrep_simulation::Point2d_<ContainerAllocator> >::stream(s, indent + "  ", v.start);
    s << indent << "finish: ";
    s << std::endl;
    Printer< ::path_planning_vrep_simulation::Point2d_<ContainerAllocator> >::stream(s, indent + "  ", v.finish);
    s << indent << "duration: ";
    Printer<float>::stream(s, indent + "  ", v.duration);
  }
};

} // namespace message_operations
} // namespace ros

#endif // PATH_PLANNING_VREP_SIMULATION_MESSAGE_STEP_H
