(cl:in-package path_planning_vrep_simulation-msg)
(cl:export '(ID-VAL
          ID
          POSITION-VAL
          POSITION
          DIRECTION-VAL
          DIRECTION
          CORNERS-VAL
          CORNERS
          PATH-VAL
          PATH
          PATH_CREATED-VAL
          PATH_CREATED
          ACTUAL_POINT-VAL
          ACTUAL_POINT
          NEXT_POINT-VAL
          NEXT_POINT
          ANGLE_TO_ACTUAL_POINT-VAL
          ANGLE_TO_ACTUAL_POINT
          ACTUAL_ANGLE-VAL
          ACTUAL_ANGLE
          SECTOR-VAL
          SECTOR
          OLD_ERROR-VAL
          OLD_ERROR
          ERROR_SUM-VAL
          ERROR_SUM
          ON_FINISH-VAL
          ON_FINISH
          MOVE-VAL
          MOVE
          ROTATION-VAL
          ROTATION
          STOP-VAL
          STOP
))