# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from path_planning_vrep_simulation/GoalData.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import path_planning_vrep_simulation.msg

class GoalData(genpy.Message):
  _md5sum = "89407f0ee13636c511a99243be5bc06e"
  _type = "path_planning_vrep_simulation/GoalData"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """int32     id
Point2d   center
Point2d[] corners
================================================================================
MSG: path_planning_vrep_simulation/Point2d
float32 x
float32 y
"""
  __slots__ = ['id','center','corners']
  _slot_types = ['int32','path_planning_vrep_simulation/Point2d','path_planning_vrep_simulation/Point2d[]']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       id,center,corners

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(GoalData, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.id is None:
        self.id = 0
      if self.center is None:
        self.center = path_planning_vrep_simulation.msg.Point2d()
      if self.corners is None:
        self.corners = []
    else:
      self.id = 0
      self.center = path_planning_vrep_simulation.msg.Point2d()
      self.corners = []

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_i2f().pack(_x.id, _x.center.x, _x.center.y))
      length = len(self.corners)
      buff.write(_struct_I.pack(length))
      for val1 in self.corners:
        _x = val1
        buff.write(_get_struct_2f().pack(_x.x, _x.y))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      if self.center is None:
        self.center = path_planning_vrep_simulation.msg.Point2d()
      if self.corners is None:
        self.corners = None
      end = 0
      _x = self
      start = end
      end += 12
      (_x.id, _x.center.x, _x.center.y,) = _get_struct_i2f().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.corners = []
      for i in range(0, length):
        val1 = path_planning_vrep_simulation.msg.Point2d()
        _x = val1
        start = end
        end += 8
        (_x.x, _x.y,) = _get_struct_2f().unpack(str[start:end])
        self.corners.append(val1)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_i2f().pack(_x.id, _x.center.x, _x.center.y))
      length = len(self.corners)
      buff.write(_struct_I.pack(length))
      for val1 in self.corners:
        _x = val1
        buff.write(_get_struct_2f().pack(_x.x, _x.y))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      if self.center is None:
        self.center = path_planning_vrep_simulation.msg.Point2d()
      if self.corners is None:
        self.corners = None
      end = 0
      _x = self
      start = end
      end += 12
      (_x.id, _x.center.x, _x.center.y,) = _get_struct_i2f().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.corners = []
      for i in range(0, length):
        val1 = path_planning_vrep_simulation.msg.Point2d()
        _x = val1
        start = end
        end += 8
        (_x.x, _x.y,) = _get_struct_2f().unpack(str[start:end])
        self.corners.append(val1)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_2f = None
def _get_struct_2f():
    global _struct_2f
    if _struct_2f is None:
        _struct_2f = struct.Struct("<2f")
    return _struct_2f
_struct_i2f = None
def _get_struct_i2f():
    global _struct_i2f
    if _struct_i2f is None:
        _struct_i2f = struct.Struct("<i2f")
    return _struct_i2f
