# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from path_planning_vrep_simulation/Step.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import path_planning_vrep_simulation.msg

class Step(genpy.Message):
  _md5sum = "e1ec2cd1e2aeecbfde1f919967aaf705"
  _type = "path_planning_vrep_simulation/Step"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """int32   number
Point2d start
Point2d finish
float32 duration
================================================================================
MSG: path_planning_vrep_simulation/Point2d
float32 x
float32 y
"""
  __slots__ = ['number','start','finish','duration']
  _slot_types = ['int32','path_planning_vrep_simulation/Point2d','path_planning_vrep_simulation/Point2d','float32']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       number,start,finish,duration

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(Step, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.number is None:
        self.number = 0
      if self.start is None:
        self.start = path_planning_vrep_simulation.msg.Point2d()
      if self.finish is None:
        self.finish = path_planning_vrep_simulation.msg.Point2d()
      if self.duration is None:
        self.duration = 0.
    else:
      self.number = 0
      self.start = path_planning_vrep_simulation.msg.Point2d()
      self.finish = path_planning_vrep_simulation.msg.Point2d()
      self.duration = 0.

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_i5f().pack(_x.number, _x.start.x, _x.start.y, _x.finish.x, _x.finish.y, _x.duration))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      if self.start is None:
        self.start = path_planning_vrep_simulation.msg.Point2d()
      if self.finish is None:
        self.finish = path_planning_vrep_simulation.msg.Point2d()
      end = 0
      _x = self
      start = end
      end += 24
      (_x.number, _x.start.x, _x.start.y, _x.finish.x, _x.finish.y, _x.duration,) = _get_struct_i5f().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_i5f().pack(_x.number, _x.start.x, _x.start.y, _x.finish.x, _x.finish.y, _x.duration))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      if self.start is None:
        self.start = path_planning_vrep_simulation.msg.Point2d()
      if self.finish is None:
        self.finish = path_planning_vrep_simulation.msg.Point2d()
      end = 0
      _x = self
      start = end
      end += 24
      (_x.number, _x.start.x, _x.start.y, _x.finish.x, _x.finish.y, _x.duration,) = _get_struct_i5f().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_i5f = None
def _get_struct_i5f():
    global _struct_i5f
    if _struct_i5f is None:
        _struct_i5f = struct.Struct("<i5f")
    return _struct_i5f
